# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5fed6b4c33701e1c1928182181b6b949aa82a7ab0db89244eb7c104b6d1e2cec18da940e1b8673568c87bdad1d1385229f4175fe6496835204fbaf13c5eba37

test:
  secret_key_base: 4f691fc8017058d98cbd497c942ec5d0fc612919a805b9b4329d19db53709d26c0011a739842f6ca51ca1cf00248a82fd2a8acfb96ec4f9a888030a5dbcefadd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
