# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bed80952dd8553a9ace8e6614ffaee77fae867b9f863321eea5544b59c9636c3cdccd67fa39924ba6ea43e7a1e672099a2ccf922a1a3975993a73585bcfdf15b

test:
  secret_key_base: 51be0394b2c73701dcdebed8577a2199d09687e7e31a69e8d35f2e0d0859abf82436ee99e47f0eb8a3258bbf6775203b8e7fea9500557c5269075c0ef6e174b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
