# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b5c18469cceb631f3b97514740268b44151579982905fd0d5a17eeab0b26840e495a0401e37bd04adf15ca929e6f67b7f2490542f392466ee46acee59304fb9

test:
  secret_key_base: 2e1d88a9a92fb4d61d25de9ee775be82479f767b2872c049f3a469f038f00e6e7f03857c5c3d94c4e1741197e43487256bbb10705bcb0b621c068d0ad75cd279

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
