# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c2a1467cca95800cf59a018b459f22067e2480d28a6ea0b305d0cfdde3a81a3bb3bf433ccc294779d9ab1685619cd6f79eb6155760b07b856b5175ef2599294

test:
  secret_key_base: b712b39fd70a133f998ed041e78467967fb79ec7d683a2e319935f166e3890cee2ecd494210c7407ccdd320dd41f8519cc62a763f431564e8c21762728e8cc54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
